---

services:
  mongodb:
    container_name: pa11y_mongodb
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

  pa11y:
    container_name: pa11y
    image: ghcr.io/croox/docker-pa11y-dashboard:latest
    environment:
      - NODE_ENV=production
    ports:
      - 127.0.0.1:4000:4000
    platform: linux/amd64
    depends_on:
      - mongodb

volumes:
  mongodb_data:
